name: ps-reconstruction
channels:
  - conda-forge
  - pytorch
  - nvidia
  - defaults
dependencies:
  - python=3.10
  - ipython
  - ipykernel
  - pytorch
  - torchvision
  - torchaudio
  - pytorch-cuda=11.7
  - numpy
  - matplotlib
  - scipy
  - h5py
  - scikit-image
  - tqdm
  - distgen
  - pip
  - openpmd-beamphysics
  - pip:
    - torchensemble==0.1.7
    - pyro-ppl
    - blitz-bayesian-pytorch
